name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-01-01
          targets: wasm32-unknown-unknown
          components: rustfmt, rust-src, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo +nightly-2023-01-01 test -Z sparse-registry

